name: aixin
version: 1
handle:
- compress:  if ( out_header["Content-type"] ~ "text/css" ) compress
- compress:  if ( out_header["Content-type"] ~ "text/javascript" ) compress
- compress:  if ( out_header["Content-type"] ~ "text/html" ) compress
- compress:  if ( out_header["Content-type"] ~ "application/msword" ) compress
- compress:  if ( out_header["Content-type"] ~ "text/plain" ) compress
